export const LOGIN_REQUEST = 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';
export const LOGOUT = 'USERS_LOGOUT';


export const FETCH_HOSTS_LOADING = 'FETCH_HOSTS_REQUEST';
export const FETCH_HOSTS_FAILURE = 'FETCH_HOSTS_FAILURE';
export const FETCH_HOSTS_SUCCESS = 'FETCH_HOSTS_SUCCESS';
export const FETCH_HOSTS_RESET = 'FETCH_HOSTS_RESET';


export const FETCH_AUDIT_LOADING = 'FETCH_AUDIT_REQUEST';
export const FETCH_AUDIT_FAILURE = 'FETCH_AUDIT_FAILURE';
export const FETCH_AUDIT_SUCCESS = 'FETCH_AUDIT_SUCCESS';
export const FETCH_AUDIT_RESET = 'FETCH_AUDIT_RESET';


export const FETCH_NETWORKS_LOADING = 'FETCH_NETWORKS_REQUEST';
export const FETCH_NETWORKS_FAILURE = 'FETCH_NETWORKS_FAILURE';
export const FETCH_NETWORKS_SUCCESS = 'FETCH_NETWORKS_SUCCESS';
export const FETCH_NETWORKS_RESET = 'FETCH_NETWORKS_RESET';


export const FETCH_NETWORKGROUPS_LOADING = 'FETCH_NETWORKGROUPS_REQUEST';
export const FETCH_NETWORKGROUPS_FAILURE = 'FETCH_NETWORKGROUPS_FAILURE';
export const FETCH_NETWORKGROUPS_SUCCESS = 'FETCH_NETWORKGROUPS_SUCCESS';
export const FETCH_NETWORKGROUPS_RESET = 'FETCH_NETWORKGROUPS_RESET';


export const FETCH_PORTOBJECTGROUPS_LOADING = 'FETCH_PORTOBJECTGROUPS_REQUEST';
export const FETCH_PORTOBJECTGROUPS_FAILURE = 'FETCH_PORTOBJECTGROUPS_FAILURE';
export const FETCH_PORTOBJECTGROUPS_SUCCESS = 'FETCH_PORTOBJECTGROUPS_SUCCESS';
export const FETCH_PORTOBJECTGROUPS_RESET = 'FETCH_PORTOBJECTGROUPS_RESET';


export const FETCH_PROTOCOLPORTOBJECTS_LOADING = 'FETCH_PROTOCOLPORTOBJECTS_REQUEST';
export const FETCH_PROTOCOLPORTOBJECTS_FAILURE = 'FETCH_PROTOCOLPORTOBJECTS_FAILURE';
export const FETCH_PROTOCOLPORTOBJECTS_SUCCESS = 'FETCH_PROTOCOLPORTOBJECTS_SUCCESS';
export const FETCH_PROTOCOLPORTOBJECTS_RESET = 'FETCH_PROTOCOLPORTOBJECTS_RESET';

export const FETCH_ACCESSRULES_LOADING = 'FETCH_ACCESSRULES_REQUEST';
export const FETCH_ACCESSRULES_FAILURE = 'FETCH_ACCESSRULES_FAILURE';
export const FETCH_ACCESSRULES_SUCCESS = 'FETCH_ACCESSRULES_SUCCESS';
export const FETCH_ACCESSRULES_RESET = 'FETCH_ACCESSRULES_RESET';

export const FETCH_RANGES_LOADING = 'FETCH_RANGES_REQUEST';
export const FETCH_RANGES_FAILURE = 'FETCH_RANGES_FAILURE';
export const FETCH_RANGES_SUCCESS = 'FETCH_RANGES_SUCCESS';
export const FETCH_RANGES_RESET = 'FETCH_RANGES_RESET';